### ISSUE TITLE
Can't install because of hashes

### ISSUE THREAD

**Issue by napnapnapnap** [152334H/tortoise-tts-fast#61]
```
python -m pip install -r ./requirements.txt
Ignoring backports-zoneinfo: markers 'python_version >= "3.8" and python_version < "3.9"' don't match your environment
Collecting bigvgan@ git+https://github.com/152334H/BigVGAN.git@HEAD
ERROR: Can't verify hashes for these requirements because we don't have a way to hash version control repositories:
    bigvgan@ git+https://github.com/152334H/BigVGAN.git@HEAD from git+https://github.com/152334H/BigVGAN.git@HEAD (from -r ./requirements.txt (line 38))
```

**Comment by AndrewBeniston** [comment]
Having the same issue, trying to get it set up in a conda env but buy luck, no more development on this by the looks :(

**Comment by vdruts** [comment]
Yep, I've tried 15x now. Conda/Python/WSL, one way, another way. All diff python pytorch versions. Always tons of errors/issues. Even the install through Poetry is fucked.

ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel

  Traceback (most recent call last):
    File "C:\Users\chlyw\AppData\Roaming\pypoetry\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\chlyw\AppData\Roaming\pypoetry\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\chlyw\AppData\Roaming\pypoetry\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\chlyw\AppData\Local\Temp\tmpv3hu9k4y\.venv\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by eloop001** [comment]
I know the answer to this one.

Simply delete the line in requirements.txt that has to do with BigVGAN.... it's around line 36 as far as I remember.

**Comment by embanot** [comment]
I don't see any line in requirements.txt that has to do with BigVGAN.  The file also only has 16 lines.  Am I doing something wrong here?

**Comment by eloop001** [comment]
I just delete the line. It has no effect.

fre. 28. apr. 2023 18.00 skrev embanot ***@***.***>:

**Comment by simeonradivoev** [comment]
just use this:
```
bigvgan @ https://github.com/152334H/BigVGAN/archive/refs/heads/main.zip ; python_version >= "3.8" and python_full_version != "3.9.7" and python_version < "3.12" \
    --hash=sha256:c5c2578c5aa48fd9e19406e374c3fddda91cf4aead10128e27cc57768392102d
```

in line 38
