### ISSUE TITLE
ImportError: BigVGAN not installed, can't use BigVGAN vocoder 

### ISSUE THREAD

**Issue by havok2-htwo** [152334H/tortoise-tts-fast#65]
No matter what I try, I always end here with these errors. Normal tortoise works fine, but not the fast one.

File "C:\Users\havok2\.conda\envs\tortoise\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "C:\Users\havok2\.conda\envs\tortoise\Scripts\app.py", line 8, in <module>
    from tortoise.api import MODELS_DIR
File "C:\Users\havok2\.conda\envs\tortoise\tortoise\api.py", line 19, in <module>
    from tortoise.models.vocoder import VocConf
File "C:\Users\havok2\.conda\envs\tortoise\tortoise\models\vocoder.py", line 13, in <module>
    raise ImportError(
    
    
    any Ideas where I took the wrong way? When I try to install BigVGan I always get an error too: ERROR: Failed building wheel for pesq but the rest looks installed correctly. I give up here. Thanks for any help.
    
    EDIT 31.03.23,
    I managed to get a new single Error: 
    
    Traceback (most recent call last):
  File "X:\stable-diffusion-infinity\anaconda3\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "X:\stable-diffusion-infinity\anaconda3\envs\ttsfast\scripts\app.py", line 8, in <module>
    from tortoise.api import MODELS_DIR
ModuleNotFoundError: **No module named 'tortoise'**

**Comment by louispaulet** [comment]
[I have made a simple docker project, want to try it ?](https://github.com/louispaulet/tortoise-tts-docker)

EDIT: archived, I use a colab.

**Comment by minuske4** [comment]
I think I have the same issue, did you ever find a fix for this?
